### ISSUE TITLE
Autocompletion broken after `->` when Belt is globally opened

### ISSUE THREAD

**Issue by gaku-sei** [rescript-lang/rescript-vscode#102]
When `Belt` is opened globally, the new `->` autocompletion feature doesn't work:

<img width="600" alt="Capture d’écran 2021-04-08 à 15 48 49" src="https://user-images.githubusercontent.com/3982371/113980845-eaa7ca00-9881-11eb-9648-21cd4cdbc066.png">

Plus, "normal" autocompletion doesn't work anymore:

<img width="523" alt="Capture d’écran 2021-04-08 à 15 49 55" src="https://user-images.githubusercontent.com/3982371/113980967-12972d80-9882-11eb-9527-9388a998fcad.png">

<img width="514" alt="Capture d’écran 2021-04-08 à 15 50 12" src="https://user-images.githubusercontent.com/3982371/113981000-1c209580-9882-11eb-96fb-527777131dbd.png">

Notice that adding a space after the `->` brings autocompletion back:

<img width="701" alt="Capture d’écran 2021-04-08 à 15 50 50" src="https://user-images.githubusercontent.com/3982371/113981085-335f8300-9882-11eb-9b1a-4a23e71b7f26.png">

Is there a way to get the "classic" autocompletion back? Or to deactivate the new `->` autocompletion feature?

**Comment by mrmurphy** [comment]
I'm seeing weird behavior as well.

Without the arrow:
<img width="338" alt="CleanShot 2021-04-09 at 13 30 00@2x" src="https://user-images.githubusercontent.com/1227109/114249918-bb539480-9937-11eb-96c0-966704acc5d1.png">


With the arrow, I don't get autocomplete on Belt module names:
<img width="815" alt="CleanShot 2021-04-09 at 13 31 52@2x" src="https://user-images.githubusercontent.com/1227109/114250010-f5249b00-9937-11eb-921e-c8b5f3b536fb.png">


And if I fully qualify the module, I just get a list of symbols that include, but aren't limited to, the Option module:
<img width="485" alt="CleanShot 2021-04-09 at 13 32 17@2x" src="https://user-images.githubusercontent.com/1227109/114250046-19807780-9938-11eb-915c-a20ee4d64685.png">


I also have Belt globally opened.

**Comment by cristianoc** [comment]
Same as https://github.com/rescript-lang/rescript-editor-support/issues/99, which is fixed in the upcoming release.

**Comment by gaku-sei** [comment]
Sorry, but it still doesn't work with rescript-vscode 1.0.8 @cristianoc  😞 
Is there anyway to disable this feature somehow?

**Comment by cristianoc** [comment]
Because that version did not change anything. Sorry it will be in the next one.
++ @chenglou

**Comment by gaku-sei** [comment]
Ah sorry I was confused as the issue got closed just when the extension v1.0.8 released, my bad 😅
Thank you for the update 👍

**Comment by cristianoc** [comment]
Should be released very soon. Meanwhile, you could install the previous version if this behavior gets in the way often.
