### ISSUE TITLE
Exception thrown on Windows 10 /Mac OS and does not seem to work

### ISSUE THREAD

**Issue by mickeyvip** [rescript-lang/rescript-vscode#25]
Tested on Windows 10, Mac MacOS 10.13.6 High Sierra.

* VSCode `1.51.1`
* `rescript-vscode` version `1.0.0`
* `bs-platform` version `8.3.3`

When opening any `res` file the output of the language server throws an exception and nothing seems to work.

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\server\out\RescriptEditorSupport.js:89:31
    at ChildProcess.exithandler (child_process.js:295:7)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 23:47:10] Connection to server got closed. Server will not be restarted.
[Error - 23:47:10] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-jsonrpc\lib\main.js:904:25)
	at Object.dispose (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:74:35)
	at LanguageClient.handleConnectionClosed (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:2309:42)
	at LanguageClient.handleConnectionClosed (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-languageclient\lib\main.js:155:15)
	at closeHandler (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:2296:18)
	at CallbackList.invoke (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at closeHandler (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-jsonrpc\lib\main.js:240:26)
	at CallbackList.invoke (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at IPCMessageReader.fireClose (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.<anonymous> (c:\Users\Mickey\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\client\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by mickeyvip** [comment]
Same happens on Mac MacOS 10.13.6 (High Sierra).

**Comment by kleyu** [comment]
So I've managed to place a `console.log` inside `RescriptEditorSupport` 
https://github.com/rescript-lang/rescript-vscode/blob/77b157e714a27c35fbaeab33344bb398a5aa9fe8/server/src/RescriptEditorSupport.ts#L45

when logging `_error`: 
```
Error: Command failed: c:\Users\jacko\.vscode\extensions\chenglou92.rescript-vscode-1.0.0\server\win32\rescript-editor-support.exe dump c:\Users\jacko\rescript-todo\pages\index.res:22:77
Fatal error: exception Invalid_argument("Filename.chop_extension")

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'c:\\Users\\jacko\\.vscode\\extensions\\chenglou92.rescript-vscode-1.0.0\\server\\win32\\rescript-editor-support.exe dump c:\\Users\\jacko\\rescript-todo\\pages\\index.res:22:77'
}
```

side note: when running `c:\\Users\\jacko\\.vscode\\extensions\\chenglou92.rescript-vscode-1.0.0\\server\\win32\\rescript-editor-support.exe dump c:\\Users\\jacko\\rescript-todo\\pages\\index.res` (without position params) in `cmd.exe` I got no error.

**Comment by yyc-git** [comment]
I have the same problem in Mac OS 10.15.1 !!!

 @chenglou How to fix it? Thanks very much~

**Comment by chenglou** [comment]
@cristianoc

**Comment by yyc-git** [comment]
I have found why I have the problem: my yarn's version is too old! haha!  

After I update the yarn to v1.22.5, and install by "yarn install", everthing is OK(no symlink error! so not need to use --no-bin-links!)!

so I don't have the problem! Thanks very much~

**Comment by mickeyvip** [comment]
Are there a special node.js/npm/yarn requirements?

**Comment by cristianoc** [comment]
@kleyu looks like the `c:` in  `c:\Users\jacko\rescript-todo\pages\index.res:22:7` confuses the command-line parsing when splitting out `:22:7` based on `:`.
I guess if one were to try to manually pass instead `pages\index.res:22:7` from the root of the project (which I guess is `rescript-todo`), it would work.
I'm going to change the parsing of command-line arguments.

**Comment by mickeyvip** [comment]
MacOS Big Sur `11.0.1`,
Node.js `10.22.1`
VSCode `1.51.1`

Working Ok.

**Comment by kleyu** [comment]
> 
> 
> @kleyu looks like the `c:` in `c:\Users\jacko\rescript-todo\pages\index.res:22:7` confuses the command-line parsing when splitting out `:22:7` based on `:`.
> I guess if one were to try to manually pass instead `pages\index.res:22:7` from the root of the project (which I guess is `rescript-todo`), it would work.
> I'm going to change the parsing of command-line arguments.

Yes! It works just fine:
```sh
$ c:\\Users\\jacko\\.vscode\\extensions\\chenglou92.rescript-vscode-1.0.0\\server\\win32\\rescript-editor-support.exe dump pages\\index.res:16:29
[{"range": {"start": {"line": 16, "character": 18}, "end": {"line": 16, "character": 47}}, "hover": "string"}]
```

**Comment by cristianoc** [comment]
There's a fix here: https://github.com/rescript-lang/rescript-editor-support/pull/35
For a quick test, one can pull the binary from the CI artifacts.
It will be available in the next bugfix release.

**Comment by cristianoc** [comment]
This PR can be used to test that the issue is fixed:
https://github.com/rescript-lang/rescript-vscode/pull/36

**Comment by mickeyvip** [comment]
@cristianoc , thank you.

Unfortunately I have no clue how to test a GitHub repo locally in VSCode.
Same goes for "CI artifacts"

**Comment by mickeyvip** [comment]
Also, I still have a problem with MacOS 10.13.6 High Sierra.

**Comment by cristianoc** [comment]
@mickeyvip a new release coming up soon, best to test that directly.
That will also include a new executable that hopefully is compatible with MacOS 10.13.6.

**Comment by cristianoc** [comment]
New release: https://github.com/rescript-lang/rescript-vscode/releases/tag/1.0.1

**Comment by mickeyvip** [comment]
Release `1.0.1` works well on Windows.
Thank you

**Comment by mickeyvip** [comment]
Release `1.0.1` works well on MacOS 10.13.6 High Sierra.
Thank you!

**Comment by mickeyvip** [comment]
Guess this can be closed
